### ISSUE TITLE
Bind Tranceiver Response issue

### ISSUE THREAD

**Issue by amigniter** [alexeevdv/react-smpp#2]
Hello,
Thanks for this project first, its a great project with really great piece of code. I personally think that's really nice code here. I gave it a try with Kannel first and with a php-smpp client which i use for testing. I've found a few issues so far. I think it can be awesome Php smpp client/server once everything is tested and fixed.  

I have one question first. In server.php, bind_transmitter
`$response = new BindTransmitterResp(CommandStatus::ESME_ROK, $pdu->getSequenceNumber());`
Why do we have here two parameters sent? BindTransmitterResp and BindResp extends Pdu class which accepts $body in constructor. Shouldn't we have $pdu->getBody() as a parameter when creating a new response?

Issue with **bind_transceiver** is that bind transceiver response gets malformed. It is missing a System Id. I think I got it fixed by adding to BindResp class:

```
public function __toString(): string
    {
        $wrapper = new DataWrapper('');
        $wrapper->writeNullTerminatedString($this->getSystemId());
        $this->setBody($wrapper->__toString());
        return parent::__toString();
    }
```
Another issue I came across is with sequence number , SubmitSm and SubmitSmResp. It is not inherited from SubmitSm via body?

Thanks

**Comment by alexeevdv** [comment]
Hey, thanks for your interest to this project. I will take a look what can be done about SystemId as soon as i get free time. It will probably take couple of days

**Comment by amigniter** [comment]
Sure, thanks @alexeevdv . My option was to add __toString() function to BindResp class as I did, which will override method in Pdu.  Now bind transceiver response is correct. 

Another issue I mentioned is SequenceNumber in SubmitSmResp:

```
$connection->on('submit_sm', function (SubmitSm $pdu) use ($connection) {
        echo 'SUBMIT SM' . PHP_EOL;
        echo "Sequence Number: " . $pdu->getSequenceNumber() . PHP_EOL;
        $response = new SubmitSmResp($pdu->getBody());
        $connection->emit('send', [$response]);
    });
```
In echo it is correct (from $pdu), but in response it is 1. Am I missing something here?

**Comment by amigniter** [comment]
Hi @alexeevdv. My appologies first for asking question without fully examining the code and how it's all done. The issue regarding **sequence number** remains i would say. I continued today examining the code.

On every PDU command, its class is instanced from the buffer with body in constructor. Properties are set in the _Factory_ (length, command, command status and sequence) and the body is set from the buffer after these first 16 bytes. Also every response class requires body in constructor, which now consists of the remaining body content (buffer - first 16 bytes).

To properly send the response we need sequence number to refer to. It is missing cause response class receives body and its not there anymore, it is set as a property in _Pdu_.

To send a response and to refer to a sequence number from PDU command I would add one more parameter to response class, the sequence number, as it's the only one required (as far as I can tell so far). If you think there is a better solution let us know please. I am writing this flow and the logics maybe for other contributors, you know all of it already as a creator.
So I'd add sequence number and it needs to be added to every response class. 

### Example _BindTransceiverResp_

`$response = new BindTransceiverResp($pdu->getBody(), $pdu->getSequenceNumber());`

### _BindResp_ class constructor

`public function __construct($body = '', int $sequenceNumber=0)`

and in constructor we set the sequence number, from the parent's _setSequenceNumber_

`$this->setSequenceNumber($sequenceNumber);`

This way, as the response class extends _Pdu_ as well, we have it in _Pdu_ and its ___toString_ method will pack it in response.

Again, your idea for the code is beautiful, and the structure as well!

This is my idea for the sequence number. Let me know what you think.

I did a couple of tests with full message flow, bind_transceiver, submit_sm and unbind. I'll see if I can attach the pcap.
[https://filebin.net/1up1iv82ihr8dduz/smpp-2021-03-09--09-25-12.pcap?t=u0wxe40z](url)

Best regards

**Comment by amigniter** [comment]
Ahhh now i see just after I wrote previous message, the method is there in _Pdu_, _setSequenceNumber_. My bad. I won't delete the message for the logic is there and someone might find it useful. It could be useful though to update the _server.php_ (skeleton), or to include some instructions so people may know how to properly use it. 

So, response is created normally, as it is. You'll need to set the **Sequence Number** using _Pdu_
`$response->setSequenceNumber($pdu->getSequenceNumber());`
or **Command Status**
`$response->setCommandStatus(CommandStatus::ESME_RINVBNDSTS);`
before sending response.

Best regards

**Comment by alexeevdv** [comment]
I've updated code a little bit and added examples for client and server 
implementations. This is still work in progress so API may change 
completely at some point

https://github.com/alexeevdv/react-smpp/tree/develop/examples
